version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_HOSTNAME: http://localhost:3001
      WDS_SOCKET_HOST: 127.0.0.1
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/build
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 3001:3000
    volumes:
      - ./backend/:/app
      - /app/node_modules
      - /app/tmp/pids
    depends_on:
      - db

  db:
    image: rethinkdb:2.4
    ports:
      - 8081:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - ~/apps/rethinkdb/data:/app